### PR TITLE
docs: separate guides & tuto sections

### PR DESCRIPTION
**Pull request by Dam-Buty**
I also removed the "Github cookbooks" section and gave them all a dedicated page (even if that page is just a link to the notebook on github). I removed a couple of pages which were duplicates

(sorry for the huge diff on mint.json, my editor auto-formatted it :neutral_face: )

The new structure looks like that : 

## guides

image

## tutorials

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/Chainlit/literal-docs/75)

### CODE REVIEW

**Comment by Dam-Buty** [comment]
@laura-ham : 

* thx for the heads-up, indeed there were 5 broken links detected. One of them isn't actually broken, i've checked both locally and in prod and it seems to work so i didn't touch it
* the content for the "Client side A/B testing" page was in fact just a copy-paste of the Jupyter notebook, and i figured that's just a risk of desync in the future. I replaced it with a direct link to the notebook, as the preview on Github is really nice looking.
* All the content in the "Prompt" guide appeared to be duplicate from content already in the "Documentation > Concepts > Prompt" section so i removed it in order to make the Guides section lighter.

What do you think ?

**Comment by laura-ham** [comment]
> @laura-ham :
> 
> * thx for the heads-up, indeed there were 5 broken links detected. One of them isn't actually broken, i've checked both locally and in prod and it seems to work so i didn't touch it
> * the content for the "Client side A/B testing" page was in fact just a copy-paste of the Jupyter notebook, and i figured that's just a risk of desync in the future. I replaced it with a direct link to the notebook, as the preview on Github is really nice looking.
> * All the content in the "Prompt" guide appeared to be duplicate from content already in the "Documentation > Concepts > Prompt" section so i removed it in order to make the Guides section lighter.
> 
> What do you think ?


* Great
* I get the idea, but then we have more guides that are copy-paste right? At least the code parts. So that still is a risk of desync. It's the case with all the tutorials we have. 
* Hmm I don't agree. Prompt guides are more elaborate than the brief versions in the Concepts, and more code heavy. I actually think its great to show guides for all sections that we have (prompt, monitoring, eval, obs), so IMO we keep those guides.

**Comment by Dam-Buty** [comment]
> * I get the idea, but then we have more guides that are copy-paste right? At least the code parts. So that still is a risk of desync. It's the case with all the tutorials we have.

I'd argue the difference is other tutorials have additional content (all the explicative text between the bits of code) that isn't present in just the code. In the case of Jupyter notebooks though, the explanations are directly in the notebook so there's not much value added by copying it verbatim.

> * Hmm I don't agree. Prompt guides are more elaborate than the brief versions in the Concepts, and more code heavy. I actually think its great to show guides for all sections that we have (prompt, monitoring, eval, obs), so IMO we keep those guides.

That's a fair point, i'll add them back

**Review by laura-ham — APPROVED** [review]
Looks good to me!

**Pull request merged**
